###
GET http://localhost:3333/api/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoia2lkdXNAbm9haCIsImVtYWlsIjoia2lkdXNAZ21haWwuY29tIiwiaWF0IjoxNjc3MzkwMTQ3LCJleHAiOjE2Nzc4MjIxNDd9.ninDEqyaQlfULlTO6_omR2dmoEahHuKLziL7QIOSSfI
###
POST http://localhost:3333/api/users/register HTTP/1.1
Content-Type: application/json

{
    "first_name" : "Kidus",
    "last_name" : "Taye",
    "email":"kidus2@gmail.com",
    "password" : "123456",
    "confirm_password" : "123456",
    "avatar" :"uploads/images/users/kidus-3/2/2023.jpg",
    "user_role" : "admin"
}

###
POST http://localhost:3333/api/users/login HTTP/1.1
Content-Type: application/json

{
    "username" : "kidus@noah",
    "password" : "123456"
}

###
GET http://localhost:3333/api/users/token HTTP/1.1

###
DELETE http://localhost:3333/api/users/logout HTTP/1.1